---
kind: pipeline
type: docker
name: default

steps:
- name: test and docs
  image: python:3.7-slim
  commands:
  - pip install . pdoc3
  - pip install -r requirements.txt
  - pytest
  - rm -rf ./docs/pgm/
  - pdoc3 ./pgm --html -o docs

- name: push
  image: alpine/git
  commands:
  - git add docs
  - git config user.name drone
  - git config user.email drone
  - git commit -m "[CI SKIP]" --allow-empty
  - git push origin main

trigger:
  branch:
  - main
  event:
  - push
